version: "3.9"

services:

    tgbot:
         build: "./"
         deploy:
             replicas: 1
         restart: "no"
         network_mode: host
         volumes:
             - ./Configs:/usr/src/tgBot/Configs
             - ./telegramBot:/usr/src/tgBot/telegramBot
         logging:
             driver: json-file
