# Generated by Django 4.1.3 on 2022-11-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('notify_text', models.TextField(blank=True, null=True)),
                ('sended', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'notify',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('ts', models.DateTimeField()),
                ('request_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField()),
                ('tg_id', models.IntegerField()),
                ('username', models.TextField(blank=True, null=True)),
                ('descrtext', models.TextField(blank=True, null=True)),
                ('first_token', models.TextField(blank=True, null=True)),
                ('token_requests_count', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
